import Head from "next/head"
import { Inter } from "next/font/google"
import { useState } from "react"
import Login from "@/components/auth/Login"
import style from '../styles/Auth.module.css'
import Registration from "@/components/auth/Registration"
import { Popup } from "@/components/widgets/Popup"
import { isValidEmail } from "@/helpers/RepresenationHelpers"
import { ERROR } from "@/values/Errors"
import axios from 'axios'
import { BACK_BASE_URL } from "@/values/Enviroment"
import { putUserAccessToken } from "@/helpers/auth"
import { useRouter } from "next/router"

const inter = Inter({ subsets: ["latin"] })

export default function Home() {
  const router = useRouter()
  const [isLogin, setIsLogin] = useState(true)
  const [haveError, setHaveError] = useState(false)
  const [errorMessage, setErrorMesagge] = useState('')

  async function signIn(data) {
    try {
      const response = await axios.post(`${BACK_BASE_URL}/login`, data)
      if (response.status === 200) {
        putUserAccessToken(response.data.token)
        router.push('/vehicles')
      } else {
        setErrorMesagge(ERROR.LOGIN_WRONG_CREDENTIALS)
        setHaveError(true)
      }
    } catch (error) {
      if (error.status == 401) setErrorMesagge(ERROR.LOGIN_WRONG_CREDENTIALS)
      else setErrorMesagge(ERROR.SERVER)
      setHaveError(true)
    }
  }

  function singleSignIn() {
    // TODO: Call back
  }

  async function signUp(data) {
    if (!checkSingUpData(data)) return
    try {
      const response = await axios.post(`${BACK_BASE_URL}/register`, data)
      if (response.status === 200) {
        setIsLogin(true)
      } else {
        setErrorMesagge(ERROR.REGISTRATION_USERNAME_EXIST)
        setHaveError(true)
      }
    } catch (error) {
      if (error.status == 409) setErrorMesagge(ERROR.REGISTRATION_USERNAME_EXIST)
      else setErrorMesagge(ERROR.SERVER)
      setHaveError(true)
    }
  }

  function checkSingUpData(data) {
    // check email pattern
    if (!isValidEmail(data.email)) {
      setHaveError(true)
      setErrorMesagge(ERROR.REGISTRATION_EMAIL)
      return false
    }
    
    // check password pattern
    if (data.password.length < 6) {
      setHaveError(true)
      setErrorMesagge(ERROR.REGISTRATION_PASSWORD)
      return false
    }

    return true
  }

  return (
    <>
      <Head>
        <title>Rent a car</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='main'>
        <div className={style.authPage}>
          <img 
            className={style.logo}
            src='/rentacar.svg'
            alt="Rentacar Logo" 
            width="300" 
            height="100" 
          />
          {isLogin ? (
            <Login 
              width={300}
              onSignInClick={(data) => signIn(data)}
              onSingleSignInClick={() => singleSignIn()}
              onSingUpClick={() => setIsLogin(false)}
            />
          ) : 
            <Registration 
              width={300}
              onSignUpClick={(data) => signUp(data)}
              onSignInClick={() => setIsLogin(true)}
            />
          }
        </div>
        <Popup
            open={haveError}
            onClose={() => setHaveError(false)}
            message={errorMessage}
            severity="error"
        />
      </main>
    </>
  );
}
