-- PayPal Payment Microservice Database Schema

-- Create paypal_payments table
CREATE TABLE IF NOT EXISTS paypal_payments (
    id SERIAL PRIMARY KEY,
    payment_id UUID UNIQUE NOT NULL,
    transaction_id UUID NOT NULL,
    merchant_order_id UUID NOT NULL,
    merchant_id INTEGER NOT NULL,
    
    -- PayPal specific fields
    paypal_order_id VARCHAR(255) UNIQUE NOT NULL,
    paypal_capture_id VARCHAR(255),
    
    -- Payment details
    amount DECIMAL(10, 2) NOT NULL,
    currency VARCHAR(3) NOT NULL DEFAULT 'USD',
    status INTEGER NOT NULL DEFAULT 0,
    
    -- Payer information
    payer_email VARCHAR(255),
    payer_id VARCHAR(255),
    payer_name VARCHAR(255),
    
    -- Timestamps
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    approved_at TIMESTAMP,
    completed_at TIMESTAMP,
    cancelled_at TIMESTAMP,
    
    -- URLs for redirection
    approval_url TEXT,
    
    -- Additional metadata
    description TEXT,
    failure_reason TEXT
);

-- Create indexes for paypal_payments
CREATE INDEX IF NOT EXISTS idx_paypal_payments_payment_id ON paypal_payments(payment_id);
CREATE INDEX IF NOT EXISTS idx_paypal_payments_transaction_id ON paypal_payments(transaction_id);
CREATE INDEX IF NOT EXISTS idx_paypal_payments_merchant_order_id ON paypal_payments(merchant_order_id);
CREATE INDEX IF NOT EXISTS idx_paypal_payments_paypal_order_id ON paypal_payments(paypal_order_id);
CREATE INDEX IF NOT EXISTS idx_paypal_payments_status ON paypal_payments(status);
CREATE INDEX IF NOT EXISTS idx_paypal_payments_merchant_id ON paypal_payments(merchant_id);

-- Add comments for documentation
COMMENT ON TABLE paypal_payments IS 'Stores all PayPal payment transactions';

COMMENT ON COLUMN paypal_payments.payment_id IS 'Unique payment identifier (UUID generated by this service)';
COMMENT ON COLUMN paypal_payments.transaction_id IS 'Transaction ID from PSP';
COMMENT ON COLUMN paypal_payments.merchant_order_id IS 'Order ID from merchant/webshop';
COMMENT ON COLUMN paypal_payments.paypal_order_id IS 'Order ID from PayPal (returned by PayPal API)';
COMMENT ON COLUMN paypal_payments.paypal_capture_id IS 'Capture ID from PayPal (when payment is captured)';
COMMENT ON COLUMN paypal_payments.status IS '0=Pending, 1=Approved, 2=Completed, 3=Cancelled, 4=Failed';
COMMENT ON COLUMN paypal_payments.amount IS 'Payment amount in specified currency';
COMMENT ON COLUMN paypal_payments.currency IS 'ISO 4217 currency code (USD, EUR, GBP, etc.)';
COMMENT ON COLUMN paypal_payments.approval_url IS 'PayPal approval URL where user completes payment';

-- Create a view for easy status queries
CREATE OR REPLACE VIEW v_paypal_payment_summary AS
SELECT 
    payment_id,
    transaction_id,
    merchant_order_id,
    merchant_id,
    paypal_order_id,
    amount,
    currency,
    CASE status
        WHEN 0 THEN 'Pending'
        WHEN 1 THEN 'Approved'
        WHEN 2 THEN 'Completed'
        WHEN 3 THEN 'Cancelled'
        WHEN 4 THEN 'Failed'
        ELSE 'Unknown'
    END as status_text,
    payer_email,
    created_at,
    completed_at
FROM paypal_payments;
