import { useState } from 'react'
import formStyle from '../styles/Form.module.css'
import style from '../styles/CardPage.module.css'
import { Button } from '@mui/material'
import Head from 'next/head'
import axios from 'axios'
import { BACK_BASE_URL } from '@/values/Enviroment'

export default function CardPage() {
    const [form, setForm] = useState({
        number: '',
        month: '',
        year: '',
        cvv: '',
    })

    function formatCardNumber(value) {
        value = value.replace(/\D/g, '')
        return value.replace(/(\d{4})(?=\d)/g, '$1 ').trim()
    }

    function handleCardNumberChange(e) {
        const formattedValue = formatCardNumber(e.target.value)
        setForm({ ...form, number: formattedValue })
    }

    function handleMonthChange(e) {
        let value = e.target.value.replace(/\D/g, '')
        if (value.length <= 2) {
            if (Number(value) > 12) value = '12'
        }
        if (value === '0') value = '1'
        setForm({ ...form, month: value })
    }

    function handleMonthBlur() {
        if (form.month.length === 1) setForm({ ...form, month: `0${form.month}` })
    }

    function handleYearChange(e) {
        const value = e.target.value.replace(/\D/g, '')
        setForm({ ...form, year: value })
    }

    function handleCVVChange(e) {
        let value = e.target.value.replace(/\D/g, '')
        if (value.length > 3) value = value.slice(0, 3)
        setForm({ ...form, cvv: value })
    }

    function isButtonDisabled() {
        return form.number == '' || form.number.length < 19
            || form.month == '' || form.year == ''
            || form.year.length < 2 || form.cvv == '' || form.cvv.length < 3
    }

    function pay() {
        const url = window.location.href;

        // Create a URLSearchParams object to parse the query string
        const params = new URLSearchParams(new URL(url).search);

        // Access specific parameters
        const mId = params.get('merchantOrderId');

        // Log the parameters
        console.log('test1:', mId);

        const month = form.month.replace(/^0+/, ''); // Remove leading zeroes
        const year = form.year;

        // Ensure month is two digits
        const formattedMonth = month.length === 1 ? `0${month}` : month;

        // Construct the date string in "YYYY-MM-DD" format
        const dateString = `20${year}-${formattedMonth}-01T00:00:00Z`;
        var data = {
            cardNumber: form.number.replace(/\s+/g, ''),
            merchantOrderId: mId,
            expDate: dateString,
            cardVerificationCode: Number(form.cvv),
        }
        console.log(form)
        console.log(data)
        
        axios.post(`${BACK_BASE_URL}/card-details`, data)
            .then(response => {
                window.location.href = `http://localhost:3000/payment?merchantOrderId=${mId}`;
            })
            .catch(_error => { 
                window.location.href = `http://localhost:3000/payment?merchantOrderId=${mId}`;
            })
    }

    return (
        <>
            <Head>
                <title>PayLink - Credit Card</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div>
                <div className="paymentTitle w-full">Card Payment</div>
                <div className='spacer-h-s' />
                <div className={style.wrapper}>
                    <div className={`${formStyle.inputWrapper} w-full`}>
                        <input
                            className={formStyle.input}
                            value={form.number}
                            placeholder='Card number'
                            onChange={handleCardNumberChange}
                            maxLength={19}
                        />
                    </div>
                    <div className={style.rowWrapper}>
                        <div className={`${formStyle.inputWrapper} ${style.inputWrapper} w-full`}>
                            <div className={style.monthYearWrapper}>
                                <input
                                    className={formStyle.input}
                                    value={form.month}
                                    placeholder='MM'
                                    onChange={handleMonthChange}
                                    maxLength={2}
                                    onBlur={handleMonthBlur}
                                />
                                /
                                <input
                                    className={formStyle.input}
                                    value={form.year}
                                    placeholder='YY'
                                    onChange={handleYearChange}
                                    maxLength={2}
                                />
                            </div>
                        </div>
                        <div className={`${formStyle.inputWrapper} w-full`}>
                            <input
                                className={formStyle.input}
                                value={form.cvv}
                                placeholder='CVV'
                                onChange={handleCVVChange}
                                maxLength={3}
                            />
                        </div>
                    </div>
                    <Button
                        disableRipple
                        className={`${formStyle.button} ${formStyle.raisedButton} w-full`}
                        onClick={pay}
                        disabled={isButtonDisabled()}
                    >
                        PAY
                    </Button>
                </div>
            </div>
        </>
    )
}